[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nodes-library"
version = "0.1.0"
description = "Reusable workflow nodes and LLM wrappers for AI workflow builder"
authors = [
    {name = "AI Workflow Builder Team"}
]
dependencies = [
    "pydantic>=2.4.0",
    "httpx>=0.25.0",
    "openai>=1.3.0",
    "anthropic>=0.7.0",
    "tiktoken>=0.5.0"
]
requires-python = ">=3.9"

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "black>=23.9.0",
    "mypy>=1.5.0"
]
langchain = [
    "langchain>=0.0.340",
    "langchain-openai>=0.0.2"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["nodes_library*"]

[tool.black]
line-length = 88
target-version = ['py39']

[tool.mypy]
python_version = "3.9"
strict = true
warn_return_any = true
warn_unused_configs = true 